change to k8s and how master/dev is deployed

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,10 +17,10 @@ jobs:
         run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY##*/})"
         id: extract_repo
 
-      - name: Build Host URL
+      - name: Build Environment Prefix
         shell: bash
-        run: echo "##[set-output name=url;]$([ "${GITHUB_REF##*/}" == "master" ] && echo ${{ secrets.HOST_URL }} || echo "beta-${{ secrets.HOST_URL }}")"
-        id: extract_host_url
+        run: echo "##[set-output name=prefix;]$([ "${GITHUB_REF##*/}" == "master" ] && echo "" || echo "beta-")"
+        id: extract_prefix
 
       - name: Push to GitHub Packages
         uses: docker/build-push-action@v1
@@ -42,22 +42,22 @@ jobs:
       - name: Deploy to Kubernetes
         shell: bash
         run: |
-          kubectl -n ${{ secrets.NAMESPACE }} set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${IMAGE_LOCATION} || echo "$SERVICE_NAME deployment not found"\
+          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=${IMAGE_LOCATION} || echo "$SERVICE_NAME deployment not found"\
           && envsubst < k8s/ingress.yml | kubectl apply -f - \
           && envsubst < k8s/service.yml | kubectl apply -f - \
           && envsubst < k8s/deployment.yml | kubectl apply -f - \
-          && kubectl -n ${{ secrets.NAMESPACE }} rollout restart deployment/${SERVICE_NAME}
+          && kubectl rollout restart deployment/${SERVICE_NAME}
         env:
           ENV: ${{ steps.extract_environment.outputs.env }}
           IMAGE_LOCATION: docker.pkg.github.com/jgoralcz/${{ steps.extract_repo.outputs.repo }}/${{ steps.extract_repo.outputs.repo }}:${{ steps.extract_environment.outputs.env }}
-          SERVICE_NAME: ${{ steps.extract_repo.outputs.repo }}
+          SERVICE_NAME: ${{ steps.extract_prefix.outputs.prefix }}${{ steps.extract_repo.outputs.repo }}
           PORT: 8443
-          HOST_URL: ${{ steps.extract_host_url.outputs.url }}
+          HOST_URL: ${{ steps.extract_prefix.outputs.prefix }}${{ secrets.HOST_URL }}
 
       - name: Deploy HOST_URL to Cloudflare
         shell: bash
         run: |
-          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records" \
+          curl -X --fail POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records" \
           -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
           -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_TOKEN}}" \
           -H "Content-Type: application/json" \
@@ -75,4 +75,4 @@ jobs:
             --data '{"type":"A","name":"$HOST_URL","content":"${{ secrets.HA_PROXY_IP }}","ttl":1,"proxied":true}' || echo "Failed updating dns record" \
           )
         env:
-          HOST_URL: ${{ steps.extract_host_url.outputs.url }}
+          HOST_URL: ${{ steps.extract_prefix.outputs.prefix }}${{ secrets.HOST_URL }}
